name: R workflow

on:
  push:
    branches: dev_actions

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.1.0'
        
    - name: Set up renv and cache
      run: |
        install.packages("renv", type = "win.binary")
        mkdir -p ${{ runner.temp }}/renv
        echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV
      shell: bash

    - name: Cache R package dependencies with renv
      uses: actions/cache@v2
      with:
        path: ${{ env.RENV_PATHS_ROOT }}
        key: ${{ runner.os }}-r-${{ hashFiles('renv.lock') }}
        restore-keys: ${{ runner.os }}-r-
      
    - name: Install dplyr and other dependencies with renv
      run: |
        library(renv)
        renv::restore()
        renv::install("dplyr")

    - name: Run simple R script
      run: Rscript -e "library(dplyr); iris %>% group_by(Species) %>% summarize(mean_sepal_length = mean(Sepal.Length))"
