name: My Workflow

on:
  workflow_dispatch:
  push:
    branches: [dev_mg]

jobs:
  my-job:
    runs-on: windows-latest
    steps:
      - name: My Step
        run: echo "Hello, world!"
      - uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Set RENV_PATHS_ROOT
        shell: bash
        run: |
          echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV
      - name: Install and activate renv
        run: |
          install.packages("renv")
          renv::restore()
        shell: Rscript {0}
      - name: Get R and OS version
        id: get-version
        run: |
          cat("##[set-output name=os-version;]", sessionInfo()$running, "\n", sep = "")
          cat("##[set-output name=r-version;]", R.Version()$version.string, sep = "")
        shell: Rscript {0}
      - name: Restore Renv package cache
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{ inputs.cache-version }}-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{inputs.cache-version }}-
      - name: Run simple R script
        run: |
          installed.packages()
          install.packages("magrittr")
          library(magrittr)
          library(dplyr)
          df <- data.frame(x = 1:10, y = 11:20)
          df_filtered <- df %>% filter(x > 5)
          print(df_filtered)
        shell: Rscript {0} 