name: cache-and-dplyr-example

on:
  workflow_dispatch:
  push:
    branches: [dev_mg]

jobs:
  my-job:
    runs-on: windows-latest
    env: RENV_PATHS_ROOT: ${{ runner.temp }}/renv
    steps:
      - name: My Step
        run: echo "Hello, world!"
      - uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Restore packages
        if: steps.cache-packages.outputs.cache-hit != 'true'
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
      - name: Use dplyr in R script
        shell: Rscript {0}
        run: |
          install.packages(magrittr)
          library((magrittr)
          library(dplyr)
          iris %>%
            group_by(Species) %>%
            summarize(mean = mean(Sepal.Length)) %>%
            print()